# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  v.name = "LB2-Mena Squidproxy"
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest:3128, host: 8081
  config.vm.provision "shell", inline: <<-SHELL
    #pre-config
    sudo su -
    apt-get update
    apt-get -y upgrade
    sudo apt-get -y install squid
    sudo apt-get -y install apache2
    sudo apt-get -y install wget
    #squid config
    service squid.service start
    service squid.service restart
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/squid.conf
    mv /etc/squid3/squid.conf /etc/squid3/squid.conf.backup
    mv squid.conf /etc/squid3/    
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/blocklist
    mv blocklist /etc/squid3/
    service squid3 restart
    #apache config
    service apache2 start
    service apache2 restart
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/index.html
    mv /var/www/html/index.html /var/www/html/index.html.backup
    mv index.html /var/www/html/index.html
    #log config
    chmod 777 /var/log/squid3/
    chmod 777 /var/log/squid3/access.log
    chmod 777 /var/log/squid3/cache.log
    mkdir /var/www/html/logs/
    mkdir /var/www/html/logs/squid3/
    chmod 777 /var/www/html/logs/squid3/
    ln -s /var/log/squid3/access.log /var/www/html/logs/squid3/access
    chmod 777 /var/www/html/logs/squid3/access
    ln -s /var/log/squid3/cache.log /var/www/html/logs/squid3/cache
    chmod 777 /var/www/html/logs/squid3/cache
    service apache2 restart
  SHELL

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
