# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest:3128, host: 8081
  config.vm.provision "shell", inline: <<-SHELL
    #pre-config
    sudo su -
    apt-get update
    apt-get -y upgrade
    sudo apt-get -y install squid
    sudo apt-get -y install apache2 apache2-utils
    sudo apt-get -y install wget
    #squid config
    service squid.service start
    service squid.service restart
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/squid.conf
    mv /etc/squid3/squid.conf /etc/squid3/squid.conf.backup
    mv squid.conf /etc/squid3/    
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/blocklist
    mv blocklist /etc/squid3/
    service squid3 restart
    #apache config
    service apache2 start
    service apache2 restart
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/index.html
    mv /var/www/html/index.html /var/www/html/index.html.backup
    mv index.html /var/www/html/index.html
    #log config
    chmod 777 /var/log/squid3/
    chmod 777 /var/log/squid3/access.log
    chmod 777 /var/log/squid3/cache.log
    mkdir /var/www/html/logs/
    mkdir /var/www/html/logs/squid3/
    chmod 777 /var/www/html/logs/squid3/
    ln -s /var/log/squid3/access.log /var/www/html/logs/squid3/access
    chmod 777 /var/www/html/logs/squid3/access
    ln -s /var/log/squid3/cache.log /var/www/html/logs/squid3/cache
    chmod 777 /var/www/html/logs/squid3/cache
    service apache2 restart
    #user auth for apache webserver
    htpasswd -cdb /etc/apache2/.htpasswd apache apache
    wget https://raw.githubusercontent.com/mena03/vagrant-webserver/main/squid-files/000-default.conf
    mv /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf.backup
    mv 000-default.conf /etc/apache2/sites-available/
    service apache2 restart
  SHELL
end
